name: 'Hillyer Custom & Classic'
favicon: null
layout_spectrum: 0.8384463018737733
typography_spectrum: 0.33484130748547614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.37545150774531066
  lightness: 0.32048383983783424
  saturation: 0.3639458881225437
  rhythmicContrast: 0.8790989327244461
purpose: []
