name: 'Hillyer Custom & Classic'
favicon: null
layout_spectrum: 0.21706
typography_spectrum: 0.74954
title: 'Hillyer Custom & Classic'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fbce31'
    - '#d5242f'
    - '#ffffff'
    - '#5b490c'
  brandStrength: 0.37545150774531066
  lightness: 0.32048383983783424
  saturation: 0.3639458881225437
  rhythmicContrast: 0.8790989327244461
purpose: []
